language: ruby
rvm:
  - 2.2
  - 2.3
  - 2.4
  - 2.5
  - 2.6
  - 2.7
  - ruby-head
  - jruby
  
jobs:
  allow_failures:
    - rvm: ruby-head
    
before_script:
  - gem install bundler
  - bundle install
  
sript:
  - ruby -Ilib:test test/*
